apiVersion: app/v1
kind: Development
metadata:
 name: mongo-db-deployment
 labels: 
  app:mongodb
spec:
 replicas:3
 matchLabels:
 app:mongodb
 
 // template -> specifiy the pod container and metadata
 template:
  metadata:
   labels:
   app:mongodb
   
  spec:
   containers:
    -name: mongodb
     image: mongodb:latest
     ports:
      - containerPort: 27012
     
---
apiVersion: app/v1
kind: Service
metadata:
 name: mongodb-service
spec:
 selector:
  app: mongodb
ports:
 - targetPort: 27012
   port: 80
